### ISSUE TITLE
query.count() with custom modifiers (sample) generates incorrect query

### ISSUE THREAD

**Issue by antonio-antuan** [xzkostyan/clickhouse-sqlalchemy#45] opened 2019-01-29 16:11 UTC
`session.query(...).count()`
That code generates something like that:
```
select count(*) from (
select ...
from table
) anon_1
```

If I trying to use sample, query will look like that:
```
session.query(...).sample(0.1)
select count(*) from (
select ...
from table
sample 0.1
) anon_1
sample 0.1
```

The same problem appears with [ARRAY JOIN](https://github.com/xzkostyan/clickhouse-sqlalchemy/pull/44)

**Comment by mrfijas** [comment] 2022-11-22 13:34
hi, wanted to create issue with sampling and array join, but I believe it would be a duplicate of this issue..
I'm using `clickhouse-sqlalchemy==0.1.8` and
```python
from sqlalchemy.sql.ddl import CreateTable

from clickhouse_sqlalchemy import engines, types, get_declarative_base, make_session
from sqlalchemy import create_engine, MetaData, Column

from clickhouse_sqlalchemy.drivers.base import ClickHouseDialect, clickhouse_dialect

uri = 'clickhouse+native://default:default@clickhouse:9000'

engine = create_engine(uri)
session = make_session(engine)
metadata = MetaData(bind=engine)

Base = get_declarative_base(metadata=metadata)


class Table(Base):
    id = Column(types.UInt32(), primary_key=True)
    arr = Column(types.Array(types.String))
    __table_args__ = (
        engines.MergeTree(
            order_by="id",
            sample_by="id",
        ),
    )


# print(CreateTable(Table.__table__).compile(dialect=clickhouse_dialect))

q = session.query(Table.arr).sample(0.2).array_join(Table.arr)
print(q.statement.compile(dialect=clickhouse_dialect))
```
was producing
```sql
SELECT "table".arr 
FROM "table" 
ARRAY JOIN "table".arr 
SAMPLE %(param_1)s
```
instead of
```sql
SELECT "table".arr 
FROM "table"
SAMPLE %(param_1)s
ARRAY JOIN "table".arr
```

when wanted to check it with latest `0.2.2` I got
```sql
SELECT "table".arr 
FROM "table"
```
with no `ARRAY JOIN` nor `SAMPLE`.

1. what am I doing wrong?
2. is sampling supported when using array join?

**Closed** 2023-05-02 17:47 UTC
