### ISSUE TITLE
join misses tables

### ISSUE THREAD

**Issue by Redysz** [xzkostyan/clickhouse-sqlalchemy#108] opened 2020-11-09 11:33 UTC
I have two identical dbs (one mysql and one clickhouse - I exported mysql data and imported to clickhouse)
When I use `sql.expression.join` with `mysql+pymysql` everything is good (explanation what "good" means below) but when I'm using `clickhouse` two tables are missing in `star.params`.

I use sqlalchemy method:

    star = sql.expression.join(left, right, onclause=onclause, isouter=is_outer)

(where `sql` is `sqlalchemy.sql`)

with `is_outer=False`, `onclause='main_table.first = first_table.id'` in `str(star.params())` for mysql driver I have:
`'main_table INNER JOIN first_table ON main_table.first = first_table.id'`
and that's good. For clickhouse:
`' INNER JOIN  ON main_table.first = first_table.id'`
what obviously is wrong.

The difference is in left and right objects passed to join method but that difference depends on database structure.

| variable | mysql+pymysql:// | clickhouse+http:// |
| ----------- | ----------- |----------- |
| left | `Table('main_table', MetaData(bind=Engine(mysql+pymysql://root:***@127.0.0.1:3307/demo_database)), Column('id', INTEGER(display_width=11), table=<main_table>, primary_key=True, nullable=False), Column('first', INTEGER(display_width=11), table=<main_table>, nullable=False), Column('second', INTEGER(display_width=11), table=<main_table>, nullable=False), Column('third', INTEGER(display_width=11), table=<main_table>, nullable=False), Column('value1', DOUBLE(precision=22, scale=6, asdecimal=True), table=<main_table>, nullable=False), Column('value2', DOUBLE(precision=22, scale=6, asdecimal=True), table=<main_table>, nullable=False), Column('utc_datetime', DATETIME(), table=<main_table>, nullable=False), schema=None)`  | `Table('main_table', MetaData(bind=Engine(clickhouse+http://default:***@127.0.0.1:8123/click_database)), Column('id', Int32(), table=<main_table>), Column('first', Int32(), table=<main_table>), Column('second', Int32(), table=<main_table>), Column('third', Int32(), table=<main_table>), Column('value1', FLOAT(), table=<main_table>), Column('value2', FLOAT(), table=<main_table>), Column('utc_datetime', DATETIME(), table=<main_table>), schema=None)` |
| right | `Table('first_table', MetaData(bind=Engine(mysql+pymysql://root:***@127.0.0.1:3307/demo_database)), Column('id', INTEGER(display_width=11), table=<first_table>, primary_key=True, nullable=False), Column('a', DOUBLE(precision=22, scale=6, asdecimal=True), table=<first_table>, nullable=False), Column('b', DOUBLE(precision=22, scale=6, asdecimal=True), table=<first_table>, nullable=False), Column('c', DOUBLE(precision=22, scale=6, asdecimal=True), table=<first_table>, nullable=False), Column('datetime', DATETIME(), table=<first_table>, nullable=False), schema=None)` | `Table('first_table', MetaData(bind=Engine(clickhouse+http://default:***@127.0.0.1:8123/click_database)), Column('id', Int32(), table=<first_table>), Column('a', FLOAT(), table=<first_table>), Column('b', FLOAT(), table=<first_table>), Column('c', FLOAT(), table=<first_table>), Column('datetime', DATETIME(), table=<first_table>), schema=None`) |

**To Reproduce**
Any db where `main_table` has column (here `main_table.first` ) with "reference" (as int) to other table's id (here `first_table.id`). Create proper `Table` object and try to join data.

**Expected behavior**
`'main_table INNER JOIN first_table ON main_table.first = first_table.id'`

**Versions**

- clickhouse-driver: 0.1.5
- clickhouse-sqlalchemy: 0.1.4
- SQLAlchemy: 1.3.20

**Comment by xzkostyan** [comment] 2020-11-19 07:16
Fixed in latest master.

**Comment by Redysz** [comment] 2020-11-19 11:31
Hello. Yes, that problem was solved. There is still a small problem with joining. When I use join with mariadb:

`
'SELECT avg(coalesce(main_table.value1, %(coalesce_1)s)) AS `metric.avg.value1`, avg(coalesce(main_table.value2, %(coalesce_2)s)) AS `metric.avg.value2` \nFROM main_table INNER JOIN first_table ON main_table.first = first_table.id \nWHERE first_table.a >= %(param_1)s AND first_table.a <= %(param_2)s AND first_table.b >= %(param_3)s AND first_table.b <= %(param_4)s AND first_table.datetime >= %(param_5)s AND first_table.datetime <= %(param_6)s'
`

and with clickhouse:
`
'SELECT avg(coalesce(main_table.value1, %(coalesce_1)s)) AS "metric.avg.value1", avg(coalesce(main_table.value2, %(coalesce_2)s)) AS "metric.avg.value2" \nFROM main_table, first_table, main_table INNER JOIN first_table ON main_table.first = first_table.id \nWHERE first_table.a >= %(param_1)s AND first_table.a <= %(param_2)s AND first_table.b >= %(param_3)s AND first_table.b <= %(param_4)s AND first_table.datetime >= %(param_5)s AND first_table.datetime <= %(param_6)s'
`

the problem is here: `FROM main_table, first_table, main_table INNER JOIN first_table` which is giving me `DB::Exception: Ambiguous column 'main_table.value1'`

These selects come from a code: `sql.expression.select(selection, from_obj=context.star, use_labels=True, whereclause=condition, group_by=group_by)`

where (in both cases)
`len(selection): 2`
`str(selection[0]): 'avg(coalesce(main_table.value1, :coalesce_1))'`
`str(selection[1]): 'avg(coalesce(main_table.value2, :coalesce_1))'`
`str(context.star): 'main_table INNER JOIN first_table ON main_table.first = first_table.id'`
`str(condition): 'first_table.a >= :param_1 AND first_table.a <= :param_2 AND first_table.b >= :param_3 AND first_table.b <= :param_4 AND first_table.datetime >= :param_5 AND first_table.datetime <= :param_6'`
`group_by: None`

**Comment by xzkostyan** [comment] 2020-11-20 22:07
I'm unable to reproduce the problem:

```python
from sqlalchemy import create_engine, Column, MetaData, func
from sqlalchemy.sql import expression
from sqlalchemy.sql.functions import coalesce

from clickhouse_sqlalchemy import Table, make_session, get_declarative_base, types, engines

uri = 'clickhouse://localhost/test'

engine = create_engine(uri)
session = make_session(engine)
metadata = MetaData(bind=engine)


main_table = Table(
    'main_table', metadata,
    Column('value1', types.UInt32, primary_key=True),
    Column('value2', types.UInt32),
    Column('first', types.UInt32),
    engines.Memory()
)
first_table = Table(
    'first_table', metadata,
    Column('id', types.UInt32, primary_key=True),
    Column('a', types.UInt32),
    Column('b', types.UInt32),
    engines.Memory()
)

join = expression.join(
    main_table, first_table, onclause=main_table.c.first == first_table.c.id,
    isouter=False
)

print(
    expression.select([
        func.avg(coalesce(main_table.c.value1, types.Int32)),
        func.avg(coalesce(main_table.c.value2, types.Int32))
    ], from_obj=join, use_labels=True, group_by=None)
        .where((first_table.c.a >= 1) & (first_table.c.a <= 2))
        .where((first_table.c.b >= 3) & (first_table.c.b <= 4))
)
```

Produces

```sql
SELECT avg(coalesce(main_table.value1, %(coalesce_1)s)) AS avg_1, avg(coalesce(main_table.value2, %(coalesce_2)s)) AS avg_2 
FROM main_table INNER JOIN first_table ON main_table.first = first_table.id 
WHERE first_table.a >= %(a_1)s AND first_table.a <= %(a_2)s AND first_table.b >= %(b_1)s AND first_table.b <= %(b_2)s
```

@Redysz can you provide minimal piece of code?

**Comment by Redysz** [comment] 2020-12-03 09:39
I'm trying. It is not the easiest job. 😃

**Comment by Redysz** [comment] 2020-12-08 08:17
Ok, I have no idea how to reproduce the problem without using the pickle module for `selection` object. I'm not as sure as before that `clickhouse-sqlalchemy` is the problem. I created package for you where statement has `FROM main_table, main_table INNER JOIN first_table` part. It should be `FROM main_table INNER JOIN` (main_table, main_table is the problem) but I can't reproduce it explicitly (using Tables for instance). It would be great if you could check it and write if it is problem with the library (`clickhouse_sqlalchemy` is used in pickle only).

[query_try1.zip](https://github.com/xzkostyan/clickhouse-sqlalchemy/files/5657754/query_try1.zip)

**Comment by xzkostyan** [comment] 2020-12-13 11:10
How should SQLAlchemy realize that plaintext `main_table` is the same as defined in python?

```python
join = text('main_table INNER JOIN first_table ON main_table.first = first_table.id')
```

It seems that it's not `clickhouse-sqlalchemy` problem it's wrong `join` usage. Plain SQLAlchemy example:

```python
from sqlalchemy import create_engine, Column, MetaData, func, BigInteger, Table, text
from sqlalchemy.orm import sessionmaker
from sqlalchemy.sql import expression
from sqlalchemy.sql.functions import coalesce

uri = 'postgresql://test:test@localhost/test'

engine = create_engine(uri)

session_cls = sessionmaker(bind=engine)
session = session_cls()
metadata = MetaData(bind=engine)


main_table = Table(
    'main_table', metadata,
    Column('value1', BigInteger, primary_key=True),
    Column('value2', BigInteger),
    Column('first', BigInteger)
)
first_table = Table(
    'first_table', metadata,
    Column('id', BigInteger, primary_key=True),
    Column('a', BigInteger),
    Column('b', BigInteger)
)

join = expression.join(
    main_table, first_table, onclause=main_table.c.first == first_table.c.id,
    isouter=False
)

print(
    expression.select([
        func.avg(coalesce(main_table.c.value1, BigInteger)),
        func.avg(coalesce(main_table.c.value2, BigInteger))
    ], from_obj=join, use_labels=True, group_by=None)
        .where((first_table.c.a >= 1) & (first_table.c.a <= 2))
        .where((first_table.c.b >= 3) & (first_table.c.b <= 4))
)

plaintext_join = text('main_table INNER JOIN first_table ON main_table.first = first_table.id')

print(
    expression.select([
        func.avg(coalesce(main_table.c.value1, BigInteger)),
        func.avg(coalesce(main_table.c.value2, BigInteger))
    ], from_obj=plaintext_join, use_labels=True, group_by=None)
        .where((first_table.c.a >= 1) & (first_table.c.a <= 2))
        .where((first_table.c.b >= 3) & (first_table.c.b <= 4))
)
```

```sql
SELECT avg(coalesce(main_table.value1, %(coalesce_1)s)) AS avg_1, avg(coalesce(main_table.value2, %(coalesce_2)s)) AS avg_2 
FROM main_table JOIN first_table ON main_table.first = first_table.id 
WHERE first_table.a >= %(a_1)s AND first_table.a <= %(a_2)s AND first_table.b >= %(b_1)s AND first_table.b <= %(b_2)s
SELECT avg(coalesce(main_table.value1, %(coalesce_1)s)) AS avg_1, avg(coalesce(main_table.value2, %(coalesce_2)s)) AS avg_2 
FROM main_table, first_table, main_table INNER JOIN first_table ON main_table.first = first_table.id 
WHERE first_table.a >= %(a_1)s AND first_table.a <= %(a_2)s AND first_table.b >= %(b_1)s AND first_table.b <= %(b_2)s
```

**Closed** 2020-12-14 18:29 UTC
